// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
// using System.Collections;
namespace csrdb
{
	public class BaseStream
	{
		protected int index;
		protected List<List<string>> data;
		protected List<string> header;
		public virtual void Close(){
			data = null;
		}
	}
}

