// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace csrdb
{
	public class CSVRelationalStream : BaseStream, IStream
	{
		const string delimiter = ",";
		const string EOL = "\n";
		public CSVRelationalStream (string str)
		{
			index = 0;
			data = new List<List<string> >();
			string[] lines = str.Split (EOL.ToCharArray());
			foreach (string line in lines  ) {
				List<string> tmpList = new List<string> ();
				foreach (string col in line.Split (delimiter.ToCharArray ())) {
					tmpList.Add (col.Trim());
				}
				data.Add( tmpList  );
			}
			header = data[0];
			data.RemoveAt(0);
		}
		public Dictionary<string,string> Next(){
			Dictionary<string,string> tuple = new Dictionary<string, string> ();

			for(int i=0;i<header.Count;++i) {

				tuple.Add(header[i], data[this.index][i]);
			}
			++index;
			return tuple;
		}

		public bool HasNext(){
			return (index + 1 < data.Capacity) ? true : false;
		}
			
	}
}

