// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace csrdb
{
	static public class Operators
	{
		static public bool GreaterThan (int a, int b) {
			return a > b;
		}
		static public bool LessThan(int a, int b) {
			return a < b;
		}
		static public bool Equal(string a, string b) {
			return a == b;
		}
	}
}

