// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace csrdb
{

	public class RenameStream :BaseStream, IStream
	{
		public delegate  bool Opfunc(int a, int b);
		protected IStream input;
		protected string attribute;
		protected string name;

		public RenameStream (IStream input, string attribute, string name)
		{
			this.input = input;
			this.attribute = attribute;
			this.name = name;
		}

		public Dictionary<string,string> Next(){
			Dictionary<string,string> tuple = this.input.Next();
			Dictionary<string,string>  result = new Dictionary<string,string> ();

			foreach (KeyValuePair<string,string> col in tuple) {
				if (col.Key == this.attribute) {
					result.Add(this.name, col.Value);
				} else {
					result.Add(col.Key, col.Value);
				}
			}
			return result;
		}

		public bool HasNext(){
			return this.input.HasNext();
		}

		override public void Close(){
			this.input.Close();
		}
	}
}

